replicador:
  environment: ctr
  description: "Configuración de desarrollo para el replicador"

# ===========================================
# DATASOURCE CONFIG (MySQL 5.7 localhost)
# ===========================================
spring:
  datasource:
    url: jdbc:mysql://<host>:3306/<db>?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: <usuario>
    password: <clave>
    driver-class-name: com.mysql.jdbc.Driver
  mail:
    host: <smtp>
    port: 587
    username: <usuario>
    password: <clave>
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # ===========================================
  # JPA / HIBERNATE CONFIG
  # ===========================================
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Mostrar parámetros de las queries (para debug)
logging:
  level:
    root: INFO
    com.example.replicacionservice: DEBUG

emails:
  values:
    recivers: rafaelrio4@gmail.com
    sender: rafaelrio4@gmail.com

origen:
  value: CTR
